### ISSUE TITLE
iptools python library issue 

### ISSUE THREAD

**Issue by harshil-shah004** [sachinkamath/ntlmrecon#3]
In iptools.IpRangeList, I can initialize the IpRange in the following way by providing a CIDR:
internalIP = iptools.IpRangeList('127.0.0.1/8')

But when I need to append a single IP in the IpRangeList, I'm unable to. 
Is there some way I can fix this, cuz the module that I'm designing, works on a single IP.
As a result, it would be meaningless to send you a pull request without fixing this.

**Comment by sachinkamath** [comment]
How about `127.0.0.1/32`?

IpRangeList() expects a CIDR block?

**Comment by harshil-shah004** [comment]
/32 works. 
So, every time I test an IP, I need to find the mask as well?
